lib/auth0/version.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

Added client headers as per auth0/ruby-auth0#31 & [SDK checklist](https://github.com/auth0/auth0-cse/blob/master/repo-checklists/SDK/checklist.md)

Client headers

---

lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

Note: The scope on the sign in needs to include `offline_access` in order to get the refresh token in the response
This should address the issue noted in #7

Updating the strategy to set the refresh token in the credentials

---

examples/ruby-on-rails-webapp/app/views/home/show.html.erb
examples/ruby-on-rails-webapp/app/views/layouts/application.html.erb

Loads lock from application.html.erb instead of loading it from home 
Fixes https://github.com/auth0/omniauth-auth0/issues/26

Fixes undefined Auth0Lock issue

---

omniauth-auth0.gemspec

Allow usage of omniauth-oauth2, which has several minor updates.

Update to omniauth-oauth2

---

.gitignore
README.md
lib/omniauth/strategies/auth0.rb

Add silent authentication functionality
Now you can pass `prompt` parameter in `redirect_to` path, and `authorize_params` method will add it to the authorization params.

Silent authentication

---

README.md

URL should be uppercase in README.md file, since it stands for Uniform Resource Locator. This pull request fix it, issue #64

URL should be uppercase outside of code

---

Gemfile
Rakefile
lib/omniauth/auth0/jwt_validator.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/auth0/jwt_validator_spec.rb
spec/spec_helper.rb

Ran:
```bash
$ rubocop --auto-correct
```
... then manually fixed the remaining 3.

Fix Rubocop errors

---

Gemfile
lib/omniauth-auth0.rb
lib/omniauth/auth0/telemetry.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/auth0/telemetry_spec.rb
spec/omniauth/strategies/auth0_spec.rb

- Add `OmniAuth::Auth0::Telemetry` to contain all telemetry-related functionality
- Add override `build_access_token` method to the spec to add the telemetry header
- [OmniAuth OAuth2 strategy parent method](https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L87)
- [Helpful example in OmniAuth-Reddit](https://github.com/jackdempsey/omniauth-reddit/blob/master/lib/omniauth/strategies/reddit.rb#L31)

Add telemetry to token endpoint

---

lib/omniauth/auth0/jwt_validator.rb
spec/omniauth/auth0/jwt_validator_spec.rb

- Added the ability to specify a custom issuer for JWT validation that differs from the provided domain
- I'm an employee at Atlassian on the Statuspage team. We are using this gem to authenticate with our internal authentication service, however the JWT generated by our internal auth service comes from auth0 servers and not from our internally hosted site. Since we make requests to our internal service, the domain is different from the generated JWT. So, to use this gem this change is necessary or else it will always fail JWT validation.
Unit tests have been added to reflect the added change, and we tested locally with our setup.

Custom issuer

---

lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

Remove telemetry from authorize URL.

Remove telemetry from authorize URL

---

lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

I changed the `OmniAuth::Strategies::Auth0#authorize_params` method to stop appending values for `connection` and `prompt` if those keys weren't present in the parsed query string.
I needed to make this change for my integration with Auth0 to work correctly. I have an Enterprise OIDC connection configured such that the `authorize_endpoint` includes `?prompt=login`, which effectively disables session management by the upstream identity provider. Without this change, OmniAuth would pass `?prompt=` to my tenant's authorized endpoint, which would in turn send `?prompt=` to my upstream OIDC authorize endpoint, despite me having configured it to use `?prompt=login` in the dashboard.
None.

Omit missing params from the authorization request

---

README.md
lib/omniauth/auth0/errors.rb
lib/omniauth/auth0/jwt_validator.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/auth0/jwt_validator_spec.rb

- Adds proper error handling in the callback phase
- Improves OIDC Compliance with ID Token Validation
- Fixes issue with JWTValidator decode returning an array, and not the expected hash
- Tests cover all scenarios of id token validation

Improved OIDC Compliance

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
lib/omniauth/auth0/jwt_validator.rb
omniauth-auth0.gemspec
spec/omniauth/auth0/jwt_validator_spec.rb

This fixes the following error:
```
NameError: uninitialized constant OmniAuth::Auth0::TokenValidationError
```
in case there's an error inside of `callback_phase`. In our case, the error was a DNS resolution error. This caused the wrong error to display in our exception reporting system (but digging in revealed the DNS error).
```
Faraday::ConnectionFailed: Failed to open TCP connection to xxxxxx.auth0.com:443 (getaddrinfo: Temporary failure in name resolution)
```
I think 2.3.1 should be released with this fix.
N/A
rspec still passes.

Fix "NameError: uninitialized constant OmniAuth::Auth0::TokenValidationError"

---

lib/omniauth/auth0/jwt_validator.rb
lib/omniauth/strategies/auth0.rb

Adds require for new error class

Fixes dependency issue

---

Gemfile.lock
README.md
lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

This adds support for the Hosted Login `screen_hint=signup` parameter. I discovered this issue while implementing Auth0 in a new Rails 6 app using Hosted Login. I noticed others had the same experience, so I thought I'd share my solution.
https://github.com/auth0/omniauth-auth0/issues/87
This can be tested by adding the `screen_hint=signup` query parameter to the `/auth/auth0` request. You should be able to observe the `screen_hint` parameter being sent to the Auth0 `/authorize` endpoint.

Add support for screen_hint=signup param

---

lib/omniauth/auth0/jwt_validator.rb
spec/omniauth/auth0/jwt_validator_spec.rb

This change adds back the verification of the JWT's signature, which was removed in [version 2.3.0](https://github.com/auth0/omniauth-auth0/releases/tag/v2.3.0).
This PR adds back signature verification for both HS256 and RS256 signed JWTs. Tests have been added to ensure that we are indeed verifying signatures, and doing so in a way that does not introduce breaking changes.
_Note:_
As this library only supports the Authorization Code flow, per the [OIDC Specification section 3.1.3.7] (https://openid.net/specs/openid-connect-core-1_0-final.html#IDTokenValidation), verifying the ID Token's signature is not strictly required:
> If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to …

Verify the JWT signature

---

lib/omniauth/auth0/jwt_validator.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

When an id_token is provided, claims should be pulled from it, versus requesting them from the userinfo endpoint.

Parsing claims from the id_token [sdk-2247]

---

lib/omniauth/strategies/auth0.rb

Previously query_string only worked on GET requests to the auth endpoint, this change takes params from GET or POST -- fixes #114

Fixes params passed to authorize [SDK-2232]

---

CHANGELOG.md
lib/omniauth-auth0/version.rb
omniauth-auth0.gemspec
spec/omniauth/strategies/auth0_spec.rb

This library was requiring `omniauth` through `omniauth-oauth2`, this patches 2.4.x with locking `omniauth` to `1.9`.  The new version of `omniauth` introduces a security fix that is a breaking change for some, and we are evaluating on either releasing a minor or a major for.

Releases 2.4.2

---

README.md
lib/omniauth/auth0/jwt_validator.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/auth0/jwt_validator_spec.rb

Auth0 Organization support added.
- invitation and org support
- org_id idtoken validation
- org documentation

Org Support [SDK-2395]

---

lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

As a aplication send username/email to auth0 universal login page. Auth0 already have feature to autofil username/email if has been sended.
Add `login_hint` on allow list of params of authorize_params
https://auth0.com/docs/universal-login/new-experience#login
`config/initializers/auth0.rb`
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
options({
login_hint: lambda do |env|
Rack::Utils.parse_query(env['rack.input'].gets)['login_hint']
end
})
provider(
:auth0,
auth0_client_id
auth0_client_secret,
auth0_domain,
callback_path: '/auth/auth0/callback',
authorize_options: ['login_hint']
)
end
```

Add login_hint to permitted params

---

CHANGELOG.md
lib/omniauth-auth0/version.rb

[Full Changelog](https://github.com/auth0/omniauth-auth0/compare/v2.5.0...v2.6.0)
**Added**
- Org Support [SDK-2395]  [\#124](https://github.com/auth0/omniauth-auth0/pull/124) ([davidpatrick](https://github.com/davidpatrick))
- Add login_hint to permitted params  [\#123](https://github.com/auth0/omniauth-auth0/pull/123) ([Roriz](https://github.com/Roriz))
[SDK-2395]: https://auth0team.atlassian.net/browse/SDK-2395

Release 2.6.0

---

README.md

Adds guidance to validating org_id claim in id tokens when not using org for the authorization endpoint

Guidance on org_id validation [SDK-2463]

---

CHANGELOG.md
lib/omniauth-auth0/version.rb
omniauth-auth0.gemspec
spec/omniauth/strategies/auth0_spec.rb

Version 3.0 introduces [Omniauth v2.0](https://github.com/omniauth/omniauth/releases/tag/v2.0.0) which addresses [CVE-2015-9284](https://nvd.nist.gov/vuln/detail/CVE-2015-9284).  Omniauth now defaults to only allow `POST` as the allowed request_phase method.
The [mitigation](https://github.com/auth0/omniauth-auth0/issues/82) to CVE-2015-9284 included using `omniauth-rails_csrf_protection` to provide CSRF protection.  You will need to install this gem and/or upgrade to the latest version 1.x.x
Now that OmniAuth now defaults to only POST as the allowed request_phase method, you will need to convert any login links to use [form helpers](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_for) with the POST method.
```html+ruby
<a href='/auth/auth0'>Login</a> …
```

Omniauth-Auth0 3.0

---

lib/omniauth/strategies/auth0.rb

- Allow forwarding of the `ui_locales` parameter to the authoriziation endpoint
This is required to set the language for the Universal Login UI, see https://auth0.com/docs/brand-and-customize/i18n/universal-login-internationalization
A request to `/auth/auth0?ui_locales=fr` should result in a french login UI when enabled in the tenant.

Add ui_locales to permitted params

---

.circleci/config.yml
Gemfile.lock

Adds Ruby 3.1 to the CI matrix.  Ruby 3.1 was released in December 2021.
This PR also includes a minimal changes to the Gemfile.lock introduced when running `bundle; bundle exec rake spec`.  Runs green locally.
[Ruby 3.1 release announcement](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/)
Note I'm seeing significant unrelated Rubocop failures.

Add Ruby 3.1 to the CI matrix

---

.circleci/config.yml
CODE_OF_CONDUCT.md
EXAMPLES.md
README.md

- This PR redesigns the readme according to latest guidelines.
- Also made a quick tweak to the CI to remove unsupported Ruby versions

[SDK-3707] Redesign readme to match new style

---

lib/omniauth/strategies/auth0.rb
spec/omniauth/strategies/auth0_spec.rb

This PR relates to Auth0 support ticket #01310199.
The `params` object that gets stored in `session['authorize_params']` for token verification is an instance of `OmniAuth::Strategy::Options`, an eventual subclass of `Hashie::Mash`. In reality, it's always treated as a regular hash, and none of `Hashie::Mash`'s features are used.
Since values in the session get serialized into a session store (e.g., `Redis::Store` in our case), this `session['authorize_params]'` value is getting serialized as an instance of `OmniAuth::Strategy::Options`. This causes problems when code that doesn't have the
`OmniAuth::Strategy::Options` class loaded tries to load the session and deserialize its contents. Since this `Options` class is unknown, the code that's loading the session blows up.
This patch simply …

Store plain Hash in session['authorize_params']

---

.circleci/config.yml
.devcontainer/devcontainer.json
CHANGELOG.md
Gemfile.lock
lib/omniauth-auth0/version.rb
lib/omniauth/strategies/auth0.rb
spec/omniauth/auth0/jwt_validator_spec.rb
spec/spec_helper.rb

**Added**
- Add ui_locales to permitted params [\#135](https://github.com/auth0/omniauth-auth0/pull/135) ([martijn](https://github.com/martijn))
**Changed**
- Store plain Hash in session['authorize_params'] [\#150](https://github.com/auth0/omniauth-auth0/pull/150) ([santry](https://github.com/santry))
- Redesign readme to match new style [\#148](https://github.com/auth0/omniauth-auth0/pull/148) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- Fix authentication hash link in code sample [\#153](https://github.com/auth0/omniauth-auth0/pull/153) ([ewanharris](https://github.com/ewanharris))
**Security**
- [Snyk] Fix for 1 vulnerabilities [\#149](https://github.com/auth0/omniauth-auth0/pull/149) ([snyk-bot](https://github.com/snyk-bot))
- Bump addressable from 2.7.0 to 2.8.0 …

Release v3.1.0

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

This fixes an issue with a test that verifies how the authorization params are written to the session (as a plain hash) that does not work using Sinatra 3. The default session store for 3 [was changed](https://github.com/sinatra/sinatra/pull/1324) `Rack::Protection::EncryptedCookie`, and this test does not take into account the cookie being encrypted.
This PR:
- Upgrades Sinatra to 3
- Uses the Sinatra 2 default cookie store of `Rack::Session::Cookie` for the purposes of tests
Fixes #162
This change was tested manually using the `debian:sid` Docker image.

fix: upgrade to Sinatra 3 and use Rack::Session::Cookie in tests

---

CHANGELOG.md
Gemfile.lock
lib/omniauth-auth0/version.rb

**Fixed**
- fix: upgrade to Sinatra 3 and use Rack::Session::Cookie in tests [\#165](https://github.com/auth0/omniauth-auth0/pull/165) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Security**
Misc dependabot package updates and version bumps.

release v3.1.1

---

Gemfile.lock

Adds all the relevant platforms to `Gemfile.lock`. This PR is in combination with setting `BUNDLE_FROZEN=true` in the Circle build, so that it stops trying to write new changes to the lockfile, resulting in uncommitted changes and causing `gem publish` to fail.

chore: add all build platforms into lockfile

---

Gemfile.lock

This PR updates the `Gemfile.lock` dependencies lockfile to resolve Snyk warnings.

Update `Gemfile.lock` dependencies

---

.devcontainer/devcontainer.json
EXAMPLES.md
lib/omniauth/auth0/jwt_validator.rb
spec/omniauth/auth0/jwt_validator_spec.rb

This PR adds support for `org_name` claim validation in the JWT validator.

[SDK-4410] Support Organization Name in JWT validation

---

lib/omniauth/auth0/jwt_validator.rb
spec/omniauth/auth0/jwt_validator_spec.rb

`org_name` claim should not be lowercased when performing claim check with `organization`.

chore: should not lowercase org_name claim

---

Gemfile.lock

Bumps [rexml](https://github.com/ruby/rexml) from 3.2.5 to 3.3.9.
Closes https://github.com/auth0/omniauth-auth0/pull/194

chore: Bump rexml from 3.2.5 to 3.3.9
